import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ethers } from "ethers";
import { useState } from "react";
import Navbar from "../Components/NavBar/Navbar";
// import LandingPage from "../Components/LandingPage/LandingPage";
import FormComponent from "../Components/Form/mainForm";

export default function Home() {
  const [Address, setAddress] = useState("");

  async function ConnectWallet() {
    if (window.ethereum) {
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      await provider.send("eth_requestAccounts", []);
      const signer = provider.getSigner();
      console.log("signer:", await signer.getAddress());
      setAddress(await signer.getAddress());
    } else {
      alert("No ETH Browser Exension Detected");
    }
  }

  function DisconnectWallet() {
    setAddress("");
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar
          Address={Address}
          ConnectWallet={ConnectWallet}
          DisconnectWallet={DisconnectWallet}
        />

        <FormComponent />
        {/* <LandingPage /> */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
